export const caseCommands = new Set([
  "developer",
  "dev",
  "creator",
  "donate",
  "donasi",
  "sawer",
  "help",
  "menu",
  "ping",
  "register",
  "daftar",
  "usermenu",
  "add",
  "addadmin",
  "addbot",
  "addplugin",
  "sp",
  "saveplugin",
  "ap",
  "addprem",
  "antibot",
  "antilink",
  "ban",
  "block",
  "broadcast",
  "bc",
  "bukadaftar",
  "deladmin",
  "delbot",
  "delprem",
  "deluser",
  "deleteuser",
  "hapususer",
  "demote",
  "follow",
  "getbio",
  "getdb",
  "group",
  "grup",
  "groupinfo",
  "hidetag",
  "ht",
  "jagagrup",
  "guard",
  "protect",
  "jpm",
  "bcgc",
  "jpmch",
  "addjpmch",
  "deljpmch",
  "listjpmch",
  "checkdb",
  "addjpmblacklist",
  "addjpmbl",
  "deljpmblacklist",
  "deljpmbl",
  "listjpmblacklist",
  "listjpmbl",
  "delmember",
  "kick",
  "linkgc",
  "gclink",
  "grouplink",
  "listadmin",
  "admins",
  "listbot",
  "listbots",
  "listuser",
  "listusers",
  "daftaruser",
  "maintenance",
  "maint",
  "mt",
  "cleanup",
  "wipedatabase",
  "wipe",
  "ownermenu",
  "promote",
  "public",
  "pushkontak",
  "pushcontact",
  "pcgc",
  "resetdb",
  "revoke",
  "resetlink",
  "resetgclink",
  "self",
  "setbotname",
  "setdesc",
  "setgroupdesc",
  "setname",
  "setgcupname",
  "setgroupname",
  "setownername",
  "setprefix",
  "shutdown",
  "offbot",
  "stats",
  "tagall",
  "tutupdaftar",
  "unban",
  "unblock",
  "premiummenu",
]);

export const ownerCommands = new Set([
  "addadmin",
  "addbot",
  "addplugin",
  "addprem",
  "ban",
  "block",
  "broadcast",
  "bukadaftar",
  "deladmin",
  "delbot",
  "delprem",
  "deluser",
  "follow",
  "getdb",
  "jpm",
  "listadmin",
  "listbot",
  "listuser",
  "maintenance",
  "ownermenu",
  "public",
  "pushkontak",
  "resetdb",
  "self",
  "setbotname",
  "setownername",
  "setprefix",
  "shutdown",
  "stats",
  "tutupdaftar",
  "unban",
  "unblock",
]);

export const premiumCommands = new Set();

export const aliasesMap = {
  dev: "developer",
  creator: "developer",
  donasi: "donate",
  sawer: "donate",
  menu: "help",
  daftar: "register",
  sp: "addplugin",
  saveplugin: "addplugin",
  ap: "addplugin",
  bc: "broadcast",
  deleteuser: "deluser",
  hapususer: "deluser",
  grup: "group",
  ht: "hidetag",
  guard: "jagagrup",
  protect: "jagagrup",
  bcgc: "jpm",
  jpmch: "jpm",
  addjpmch: "jpm",
  deljpmch: "jpm",
  listjpmch: "jpm",
  checkdb: "jpm",
  addjpmblacklist: "jpm",
  addjpmbl: "jpm",
  deljpmblacklist: "jpm",
  deljpmbl: "jpm",
  listjpmblacklist: "jpm",
  listjpmbl: "jpm",
  kick: "delmember",
  gclink: "linkgc",
  grouplink: "linkgc",
  admins: "listadmin",
  listbots: "listbot",
  listusers: "listuser",
  daftaruser: "listuser",
  maint: "maintenance",
  mt: "maintenance",
  cleanup: "maintenance",
  wipedatabase: "maintenance",
  wipe: "maintenance",
  pushcontact: "pushkontak",
  pcgc: "pushkontak",
  resetlink: "revoke",
  resetgclink: "revoke",
  setgroupdesc: "setdesc",
  setgcupname: "setname",
  setgroupname: "setname",
  offbot: "shutdown",
};
