export const settings = {
    botName: "Palantir Bot",
    ownerName: "Pentagon",
    ownerNumber: "6287847566690",
    pairingNumber: "6287847566690",
    watchdogNumber: "62811111111",
    usePairingCode: true,
    public: true,
    prefix: ".",
    autoRead: false,
    autoOnline: false,
    cooldownTime: 3000,
    stickerPackName: "Palantir Bot Stickers",
    stickerAuthor: "Pentagon",
    image: 'assets/image.png',
    linkTitle: "Palantir Bot",
    linkBody: "Modular & High-Performance WhatsApp Bot",
    linkUrl: "https://github.com/rizqianymore/rizzerbot",
    linkImage: "assets/banner.png",
    newsletterJid: "120363202796245235@newsletter",
    newsletterName: "Palantir Bot Updates",
    danaNumber: "[Masukkan Nomor Dana]",
    gopayNumber: "[Masukkan Nomor Gopay]",
    ovoNumber: "[Masukkan Nomor OVO]",
    saweriaUrl: "https://saweria.co/example",
    rizzQuotes: [
        "Are you a keyboard? Because you're just my type.",
        "Are you a Wi-Fi signal? Because I'm feeling a really strong connection.",
        "Do you believe in love at first sight, or should I walk by again?",
        "Are you a magician? Because whenever I look at you, everyone else disappears.",
        "Is your name Google? Because you have everything I’ve been searching for.",
        "Are you a camera? Because every time I look at you, I smile.",
        "If you were a triangle, you'd be acute one.",
        "Do you have a map? I keep getting lost in your eyes.",
        "Are you a carbon sample? Because I want to date you.",
        "We're not socks, but I think we'd make a great pair."
    ]
};
